version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3.9-management"
    container_name: rabbitmq-local
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: "redis:latest"
    container_name: redis-local
    ports:
      - "6379:6379"
      - "8001:8001"

  server:
    image: server:latest
    container_name: server
    # restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: development
      PORT: 3000
      QUEUE_HOST: rabbitmq
      QUEUE_PORT: 5672
      QUEUE_USER_NAME: guest
      QUEUE_USER_PASSWORD: guest
      REDIS_HOST: redis
      REDIS_URL: 'redis://redis:6379'
      REDIS_PASS: 'requirepass' 
      RABBITMQ_HOST: rabbitmq
      REDIS_PORT: 6379
      CACHE_EXPIRY_SECONDS: 10000
    depends_on:
      - rabbitmq
      - redis

  worker:
    image: worker:latest
    container_name: worker
    env_file:
      - ./worker/.env
    environment:
      NODE_ENV: development
      QUEUE_HOST: rabbitmq
      QUEUE_PORT: 5672
      QUEUE_USER_NAME: guest
      QUEUE_USER_PASSWORD: guest
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: 'redis://redis:6379'
      REDIS_PASS: 'requirepass'  
      RABBITMQ_HOST: rabbitmq
      GEMINI_API: ${GEMINI_API}
      CACHE_EXPIRY_SECONDS: 10000
    depends_on:
      - rabbitmq
      - redis
    pids_limit: 40
    cpus: 0.5
    mem_limit: 300M
